### ISSUE TITLE
Need to provide hints to increase buffering for power consumption reasons

### ISSUE THREAD

**Issue by cwilso** [WebAudio/web-audio-api#348] opened 2014-08-25 15:47 UTC
It's been requested that we enable a batching mechanism to let users of the API tell us to process a batch of frames at a time (rather than the lowest latency we can support on a given system), trading off higher latency for applications that would rather minimize power (e.g. a simple background-music-playback app).

**Comment by bjornm** [comment] 2015-08-04 15:05
Hello! Just stumbled across this item, it looks really good. 

I'm just wondering what the status is? The latency in Chrome has gone up for Mac from 25ms to 35ms, see this commit:

https://chromium.googlesource.com/chromium/src/+/ca469461bbd554ecddc82ea91d2cef7f3df5502e

It seems, it is awaiting a spec proposal before a fix to AudioContext and thereby the underlying audio pipeline can be added. So if you add this to the spec, then maybe Chrome dev can implement that change and revert the latency to a lower figure once more. It would be awesome.

Thanks,
Björn

**Comment by joeberkovitz** [comment] 2015-09-29 15:09
Note that anything we do with the AudioContext constructor should be considered in light of the need to obtain AudioContexts for specific output devices in the future (e.g. a device ID might need to be passed in).

**Comment by joeberkovitz** [comment] 2015-10-27 01:03
TPAC 2015:

`AudioContext` will take a new property bag argument allowing specification of this category as an option. 

```
enum AudioContextPlaybackCategory {"balanced",  "interactive", "playback"};
```

`"balanced"`: balance latency and stability/power consumption
`"interactive"`: lowest latency possible without glitching
`"playback"`: latency not important, sustained playback without interruption is priority. Lowest power consumption.

The default category is `"interactive"`.

NOTE: the `AudioContext` property-bag argument will now absorb other proposed initialization data for AudioContext (e.g. output device).

**Comment by billhofmann** [comment] 2015-10-30 03:57
Folks: working on this, what I'm thinking is the interface looks something like this:

[Constructor(optional AudioContextInit contextInit)]
interface AudioContext : EventTarget { ...

where AudioContextInit is a dictionary that has the buffering hint, but can also have the init id. 

Whaddya think?

**Comment by billhofmann** [comment] 2015-10-30 04:29
ok.  my pull has that approach.

**Comment by rtoy** [comment] 2015-10-30 16:22
I think I would prefer the name AudioContextOption(s) instead of AudioContextInit.

**Comment by hoch** [comment] 2015-10-30 17:05
:+1: for `AudioContextOptions`.

**Comment by hoch** [comment] 2015-10-30 17:16
I also like AudioContextOptions slightly better - I've been thinking something like this. (Note that `sinkId` and `sampleRate` are just shown as an example.)

```webidl
dictionary AudioContextOptions {
  DOMString? sinkId;  
  AudioContextPlaybackCategory? playbackCategory = 'interactive';
  long? sampleRate;
}
```

**Comment by billhofmann** [comment] 2015-10-31 02:56
Options works fine for me.  For now, unless someone objects, I'm going to leave out sinkID and sampleRate.  From a WebIDL PoV, does saying = 'interactive' flag the default value?

**Comment by hoch** [comment] 2015-10-31 03:00
I believe so - I simply followed [W3C WebIDL spec](http://www.w3.org/TR/WebIDL/#dfn-dictionary-member-default-value). Also I absolutely agree with you. I put `sinkId` and `sampleRate` there just as an example.

**Comment by foolip** [comment] 2016-01-27 04:27
There's an [Intent to Implement and Ship: WebAudio: Add buffering/latency hint via playbackCategory](https://groups.google.com/a/chromium.org/d/msg/blink-dev/FyxYC3TE8ck/XAibw9SOAAAJ) on blink-dev where I've questioned the proposed hint-based API. Let me summarize here.

Audio output APIs on native platforms are not restricted to a similar 3-value `playbackCategory` when deciding on the trade-offs around latency, so the enum must internally be mapped to some numeric latency for each device. This would make the `playbackCategory` API less powerful than native platforms, and this does not seem necessary.

If the API were to use a numerical requested latency, and the actual latency used will always be in the range of latencies allowed by the `playbackCategory` API, then this would be strictly more powerful, with no apparent downside. In addition, I would propose:
 * A readonly attribute for the actual latency, if that is useful. (Not sure about usefulness.)
 * A method to ask for a latencies that optimizes for battery usage (possibly not the maximum latency, as @jernoble has pointed out), WebRTC (I think this is what "interactive" is for), or whatever other use cases are important, recommended for everyone who does not need low-level control.

Please help me understand if there's any fundamental reason why this, or something similar, would not be workable, or if there's reason to think that the outcome in practice would be worse.

**Comment by dalecurtis** [comment] 2016-01-27 18:22
Practically it's a lot of overhead for a value we'll likely ignore 90% of the time; which was my original objection to this. It's a pain trying to find a buffer size which avoids glitching -- especially in Chrome's case where we have to transfer the audio data across processes in response to an OS callback.

I don't want Chrome (or its users) to have to sign up for mucking about with buffer sizes in a multi-platform world. I don't even like doing it myself :) It seems far more practical to map a set of enums to a   loosely-defined categories which can vary across platforms.

Largely my desired outcome for this API is better music playback and real time communication interactions. Today these are hampered by the less-resilient-to-glitching, higher-power buffer size always chosen by WebAudio. Ideally (in my eyes of course) instead WebAudio should be slaved to the buffer size required for these application.

For playback that's: 20ms rounded to a power-of-two on POSIX variants and a flat 20ms on Windows. For RTC it can vary depending on the microphone sample rate and platform.

I also don't want us to have to sign up for ensuring all buffer sizes in a range playout smoothly, because as mentioned its a tweaking game which has taken years to get right for the majority of users.

**Comment by foolip** [comment] 2016-01-28 03:47
Thanks for elaborating, @dalecurtis!

> Ideally (in my eyes of course) instead WebAudio should be slaved to the buffer size required for these application.

That makes a lot of sense, does the `playbackCategory` API achieve that? I assume that a single system can have multiple microphones with different sampling rates, and that the buffer size for RTC is therefore not a constant even on a single device. If there are multiple audio output devices with different sampling rates, it sounds like media elements would also not have a fixed buffer size.

In order to slave the AudioContext to the buffer size required by the input, then perhaps the API should be of the type "this is the `MediaStream`/`HTMLMediaElement` that I will use as the primary input, please pick a matching latency"? Something like `new AudioContext({ optimizeForThis: mediaStream })` or `new AudioContext({ optimizeForThese: [mediaElement, mediaStream] })`?

> I also don't want us to have to sign up for ensuring all buffer sizes in a range playout smoothly, because as mentioned its a tweaking game which has taken years to get right for the majority of users.

That wouldn't have to be the case even with a numeric latency, it could be restricted to only those values that have been tweaked to perfection. (If there are less than 3 perfectly tweaked latencies, then it'd be silly of course.)

**Comment by rtoy** [comment] 2016-01-28 16:29
On Wed, Jan 27, 2016 at 7:47 PM, Philip Jägenstedt <notifications@github.com
> wrote:

Thanks for elaborating, @dalecurtis <https://github.com/dalecurtis>!
>
> I also don't want us to have to sign up for ensuring all buffer sizes in a
> range playout smoothly, because as mentioned its a tweaking game which has
> taken years to get right for the majority of users.
>
> That wouldn't have to be the case even with a numeric latency, it could be
> restricted to only those values that have been tweaked to perfection. (If
> there are less than 3 perfectly tweaked latencies, then it'd be silly of
> course.)
>

​Can't speak for other items, but for webaudio only, any latency above the
minimum we support today should work fine for audio output.  Once you throw
in audio input, media streams, rtc, etc., it is probably quite messy.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/348#issuecomment-175948191>
> .
>



-- 
Ray

**Comment by dalecurtis** [comment] 2016-01-29 18:33
The category API does resolve this, but not as well as your optimizeForThis idea; which sounds very appealing. It prevents users from shooting themselves in the foot by say requesting real time latency with basic playback with the category based API.

I believe tommi@ is lurking on this thread, so he can chime in if I'm wrong, but WebRTC will (soon) mix and resample as necessary to facilitate a single output stream (required for echo cancellation) - so this shouldn't be a problem in the future (if it is even now).

As far as the numeric value approach I don't see the value of presenting a false choice. I.e., it seems only valuable if we allow users to choose any buffer size (in reason). Based on bug reports from pro audio users, I'd wager most (the majority?) of users who would want to tweak their sizes want a lower value than we allow today (i.e. unrestricted numeric) and wouldn't care much for the optimizeForThis or category APIs.

**Comment by tomasgunn** [comment] 2016-02-04 12:28
While I've taken a look at this thread occasionally, I'm not fully up to speed, so apologies if I have no clue what I'm talking about :)

So, yes, we're working on mixing webrtc audio in Chrome along with other audio, resample as appropriate, group by buffer sizes etc.  We believe there are problems, especially on Mac, with how we do audio IO and one of our goals is to reduce IPC and the chance of running into glitches.

My .02$ on categories and buffer sizes:

As a recording musician, I would like to be able to tweak buffer sizes directly.  That's what I do in Cubase, Pro Tools, Tracktion etc.  If Chrome is to be more than a toy in this regard, I would expect the same sort of power to be available.  I'm also a believer in not taking power away from app developers and do their thinking for them.  If that means more footguns will be available, that's acceptable :)

For general playback of audio/video and configuring WebRTC sessions, I think it makes sense to leave it up to the browser do decide and be able to have categories such as 'rtc', something for non-interactive playback, something for low power etc.

**Comment by foolip** [comment] 2016-02-08 14:18
OK, so from @rtoy in https://github.com/WebAudio/web-audio-api/issues/348#issuecomment-176264372 it sounds like for Web Audio that doesn't interact with `HTMLMediaElement` or `MediaStream`, a large range of latencies would be possible.

And for `HTMLMediaElement` or `MediaStream`, it's not quite clear to me if using the `playbackCategory` enum would allow for the "WebAudio should be slaved to the buffer size required" that @dalecurtis wishes for in https://github.com/WebAudio/web-audio-api/issues/348#issuecomment-175780999, or if it would be necessary to provide the source at context creation time as in https://github.com/WebAudio/web-audio-api/issues/348#issuecomment-175948191.

@tomasgunn, I agree that the web platform should match the powers of native platforms to the fullest extent possible, and the challenge here is to understand to which extent it *is* possible.

@rtoy, this is blocking the blink-dev intent, do you feel like you have any way of moving this forward, or does everything suggested so far seem impractical?

**Comment by mdjp** [comment] 2016-02-11 19:51
Reopened after call - needs further discussion

**Comment by rtoy** [comment] 2016-02-18 22:34
@foolip Sorry for the delay. It looks like we'll need to discuss this further.  I sympathize with @tomasgunn's desires for fine control, but I also defer to @dalecurtis expertise in making chrome audio glitch free.  Chrome's webaudio implementation depends ultimately on the work that @dalecurtis and others have done.

**Comment by tomasgunn** [comment] 2016-02-18 23:14
I'm also a part of that work :-)

**Comment by joeberkovitz** [comment] 2016-02-25 17:26
@rtoy to develop proposal

**Comment by rtoy** [comment] 2016-02-25 17:27
Possibly allowing both the category string and a specific number.

**Comment by rtoy** [comment] 2016-02-29 19:18
How about this:

```
dictionary AudioContextOptions {
   (AudioContextPlaybackCategory or double) playbackCategory = "interactive";
};
```

When `playbackCategory` (do we need a new name?) is double, it specifies desired buffer size in sec.  This is a hint.  The browser should try to accommodate the request as best as possible, but no guarantees on whether it honored your request, or even if it sounds ok.

Do we also need an attribute to specify the actual size that the browser used?  That might be useful to adjust the graph in some appropriate way?

Probably need some hints like a category of 0 is the same as "interactive".  If category is > x sec, it's the same as "playback".  (What is the value of x?  100 ms? 1 sec?)  Don't know how to specify "balanced" as a number. I suspect we can't really.

So many issues to sort out....

**Comment by foolip** [comment] 2016-03-02 17:12
> Do we also need an attribute to specify the actual size that the browser used? That might be useful to adjust the graph in some appropriate way?

I'm not sure how to use it, but that sounds sensible, not too dissimilar from `OfflineAudioContext.prototype.length`.

> Don't know how to specify "balanced" as a number. I suspect we can't really.

I suppose the spec doesn't need to say what the number is for any of the categories, only that interactive ≤ balanced ≤ playback. But if "balanced" is primarily intended for WebRTC, wouldn't it internally simply be a delay that is imperceptible for voice (~50ms?) and then just clamped to what the platform can handle? If so, then presumably the web app could just handle this by asking for 50ms directly.

Then there is of course also the question about syncing clocks, if the `new AudioContext({ optimizeForThis: mediaStream })` idea makes any sense or not.

**Comment by rtoy** [comment] 2016-03-02 18:02
On Wed, Mar 2, 2016 at 9:12 AM, Philip Jägenstedt <notifications@github.com>
wrote:

> Do we also need an attribute to specify the actual size that the browser
> used? That might be useful to adjust the graph in some appropriate way?
>
> I'm not sure how to use it, but that sounds sensible, not too dissimilar
> from OfflineAudioContext.prototype.length.
>

​I'm kind of guessing on its usefulness, but I like introspection if what I
ask for might not have actually happened.​

​I'm mostly thinking of cases like requesting 1 microsec (silly, yes) which
isn't supported. It might be useful to know that instead of 1 microsec, 3
ms is used.

Or maybe the browser will round the time to be a multiple of 128 frames to
reduce CPU peak processing requirements.  That might be nice to know too.​

> Don't know how to specify "balanced" as a number. I suspect we can't
> really.
>
> I suppose the spec doesn't need to say what the number is for any of the
> categories, only that interactive ≤ balanced ≤ playback. But if "balanced"
> is primarily intended for WebRTC, wouldn't it internally simply be a delay
> that is imperceptible for voice (~50ms?) and then just clamped to what the
> platform can handle? If so, then presumably the web app could just handle
> this by asking for 50ms directly.
>

​I think if the user said 50 ms, we give 50 ms if possible. If you want to
interact with WebRTC, use "balanced".  Anything else would probably be
wrong unless you looked at the actual implementation of the browser.​


> Then there is of course also the question about syncing clocks, if the new
> AudioContext({ optimizeForThis: mediaStream }) idea makes any sense or
> not.
>
​A different but closely related issue. I don't know what the best approach
would be.​


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/348#issuecomment-191329665>
> .
>



-- 
Ray

**Comment by rtoy** [comment] 2016-03-21 20:02
As discussed in the last teleconference, here is a proposal.

    dictionary AudioContextOptions {
       (AudioContextLatencyCategory or double) latencyHint = "interactive";
    };

`AudioContextLatencyCategory` is just a new name for `AudioContextPlaybackCategory`.  The category is the preferred method for specifying the latency.  For fine control, `latencyHint` can be a number specifying the latency in seconds.  The browser will adjust its internal processing to satisfy the hint as best as possible.

The `AudioContext` adds a new attribute

    readonly double processingLatency;

The value of `processingLatency` is the actual value (in sec) used by the browser.

For example, at 44.1 kHz, if a browser implements double buffering for the internal audio processing and can process audio at 128 frames, `processingLatency` would be `2*128/44100` =  5.804e-3.

**Comment by hoch** [comment] 2016-03-21 20:31
This looks good to me, but:
1. Not sure `(AudioContextLatencyCategory or double)` as type is possible.
2. We might want to clarify `AudioContext.processingLatency` merely represent the latency caused by Web Audio API, not the underlying hardware or the subsequent processing outside of the browser.

**Comment by rtoy** [comment] 2016-03-21 23:02
I tried `AudioContextLatencyCategory or double)` is allowed in WebIDL and it seems to work in Chrome.

Yes, we need to mention that the latency here does does not include the rest of the audio system.

**Comment by foolip** [comment] 2016-03-22 03:32
The `latencyHint` proposal makes sense to me. A union type like this is used in https://w3c.github.io/webvtt/#the-vttcue-interface so it does work.

The "pass through" semantics first mentioned in https://github.com/WebAudio/web-audio-api/issues/348#issuecomment-57837507 still seem like an unsolved problem, but it seems quite likely that an API for that would be (syntactically) orthogonal to `latencyHint` / `processingLatency` and even with that problem solved there would be purse Web Audio cases where latency control is useful.

**Comment by rtoy** [comment] 2016-03-23 20:37
I think the category "balanced" is meant for the pass through case.  There's a problem if the appropriate value for, say, an audio tag vs WebRTC is different, though.

**Comment by foolip** [comment] 2016-03-24 03:42
Is it going to be the same even for all WebRTC-related `MediaStream`s? It's not obvious to me that the audio from a local microphone and that coming from a remote `RTCPeerConnection` would have the same "pass through" latency.

**Comment by mdjp** [comment] 2016-04-07 15:31
Change processingLatency to baseLatency to avoid confusion. Otherwise accept revision to add numeric value.

**Comment by hoch** [comment] 2016-04-07 15:39
Note: this constructor option and the latency property are only valid for real-time audio context.

**Comment by alvestrand** [comment] 2016-04-11 09:31
/sub
The latency constraint (a request to getUserMedia) is already in that spec.

**Comment by rtoy** [comment] 2016-04-14 01:30
Question.  If the user specified "interactive" (or some other enum), what should `baseLatency` return?  Should it be the actual latency or "interactive"?  As currently spec'ed in #775, we need to return a double, but should it also support enums?  A double is nice, though.

Finally, it's the time in sec.  A value in msec would be more natural, but does make it different from all other time values in WebAudio.

**Comment by foolip** [comment] 2016-04-14 09:21
Having `baseLatency` always be a double would make sense to me. Otherwise there's presumably no way of knowing what "interactive" mapped to, and if knowing `baseLatency` is ever useful it ought to be potentially useful in that case as well.

**Comment by tomasgunn** [comment] 2016-04-14 09:29
Agree that double would be useful even if it's best effort.

**Comment by rtoy** [comment] 2016-04-14 17:22
I actually like a numeric value for all cases too. I'm going to leave it as double, then.

**Closed** 2016-05-12 12:10 UTC
Labels: Ready for Editing
