### ISSUE TITLE
Question about how to help resolve inconsistencies in Web Audio implementations between browsers

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#1842] opened 2019-03-21 15:29 UTC
This is a message from public-audio@w3.org:

---
> Greetings,
> 
> I work for an organization that develops interactive educational web-based simulations (see https://phet.colorado.edu for more info).  We are currently adding sound to many of our simulations, and I’m running into issues due to inconsistencies in the implementation of Web Audio across the leading browsers.  I already reported one bug to Mozilla, which they have agreed to resolve, but some of the other problems that I’m finding are a little less clear as to which browser is incorrect, or if the spec is just vague on some points.  I was wondering if there was someone there that I could work with to help sort some of this out.  I’m happy to provide code that demonstrates the differences in order to minimize the level of effort on your end, and I’m also happy to report the issues to Chrome/Mozilla/Apple/Microsoft once I’m clear on which browsers are in violation of the spec.
> 
> Thanks and Best Regards,
>  
> John Blanco
> PhET Interactive Simulations
> University of Colorado, Boulder
---

**Comment by hoch** [comment] 2019-03-21 15:30
A response written by @padenot:

> If you could write a short document outlining the various problems you're seeing, one of us could quickly assess the situation, and determine whether a particular implementation is not respecting the spec (and in fact, no implementation fully implement every little detail of the spec right now), or if the spec is simply unclear about something. It could be (and has historically been) both reasons, so without looking into the particular problem, it's hard to tell. Out of this, we'll probably end up writing Web Platform Tests (which are tests being run on all implementations), to make it easy to determine which implementation is (are) correct and which is (are) wrong.

**Comment by hoch** [comment] 2019-03-21 15:53
As a reference point: https://webaudio.github.io/web-audio-api/implementation-report.html

We will be waiting for the response (a collection of evidences) from the reporter.

**Comment by jbphet** [comment] 2019-03-26 19:48
I'm planning to add several examples of differences that I'm seeing in the Web Audio behavior in across the popular browsers to this GitHub issue.  Please let me know if these should be going somewhere else.

The first is a difference in the behavior of the `linearRampToValueAtTime` method.  On Chrome, it seems to start the ramp at the time the method is invoked.  On Firefox, Chrome, and Edge it seems to calculate the ramp based on the previous event.  I'm not sure which behavior is closer to what the spec intended, but I'm finding it problematic when making frequent volume changes and wanting to hear smooth transitions from the current gain setting to the specified value.  My guess is that this method was intended more for the creation of amplitude envelopes, and clients could make several calls in a row to define the envelope as a sequence of ramps, but I'm not sure and the online examples don't make this very clear.  At any rate, if the behavior were consistent across browsers, it would be easier to figure out how this method can and should be applied.

The provided example code creates an oscillator and hooks it up to a gain node when the "Start" button is pressed.  It then periodically calls  `linearRampToValueAtTime` every two seconds with a ramp time of 1/2 second.  On Chrome, smooth level transitions are heard.  On Firefox, Safari, and Edge, the volume transitions are abrupt.  On some of the browsers in the 2nd list, I'm hearing a bit of residual oscillator sound during the downward ramp of the volume.  Pressing the "Stop" button stops and disconnects the oscillator.

A live link to the test document can be found at https://phet-dev.colorado.edu/jb-tests/periodic-linear-ramp-tester.html (this link should be live for at least a month, no guarantees after that time), and the code can be found at https://github.com/phetsims/tambo/blob/master/html/periodic-linear-ramp-tester.html.

Please let me know if any additional information is needed.

**Comment by rtoy** [comment] 2019-03-26 21:44
Thanks for the test code.  A quick read of the code indicates that this what you're doing:
```
gain.gain.setValueAtTime(0, context.currentTime);
osc.connect(gain).connect(context.destination);
osc.start()

// Loop the following "forever"
while (1) {
  gain.gain.linearRampToValueAtTime(1, context.currentTime + 0.5);
  // Wait 2 sec
  gain.gain.linearRampToValueAtTime(0, context.currentTime + 0.5);
  // Wait 2 sec
}
```

While I certainly like how Chrome sounds in this example, I do think
Chrome is wrong and Firefox et al is doing what the spec says it
should be doing.  The glitches you hear are expected.

I'll have to check Chrome's code, but after a certain time (a few
render quanta at most), old events are removed from the timeline.
Then the call to linearRamp has no preceding event so chrome inserts a
setValueAtTime(intrinsicValue, context.currentTime).  Hence the nice
smooth ramp up and down.

**Comment by jbphet** [comment] 2019-03-26 22:04
Thanks @rtoy - that sounds reasonable.

**Comment by jbphet** [comment] 2019-03-26 22:31
The next test case is changing gain in the absence of a signal.  The test creates an oscillator and a gain node, hooks them up without starting the oscillator, then calls `setTargetAtTime` on the gain node, then sets up a delayed call to start the oscillator in 1 second.  It sets up one more delayed call to read the gain value 1 second later. In Chrome and Firefox, no sound is heard when the oscillator is started, which I *would* interpret to mean that the gain changes right away, except that Chrome reports a gain value of 1 at this point in time, and 0 a second later when the gain value is re-read.  Firefox always reports a gain value of 1, but I don't think Firefox supports reading of gain values (which is another difference in behavior).

In Safari and Edge, a sound is heard when the oscillator starts, and the gain values that are output seem to indicate that the movement of the gain value towards the target doesn't start until a signal is detected at the gain node.

Again, I'm not sure which of these is out of spec, but for my purposes, the behavior of Chrome and Firefox is what I would have expected in the sense that no sound is heard.

A live link is available at https://phet-dev.colorado.edu/jb-tests/gain-change-without-signal-tester.html and the source code is at https://github.com/phetsims/tambo/blob/master/html/gain-change-without-signal-tester.html.

**Comment by rtoy** [comment] 2019-03-27 16:17
@jbphet Thanks for these test cases.  In the future, can you file a separate issue for item?  It will be really hard to keep track of things if they're all in one giant issue.

We really appreciate your help in finding these difference!

I'm going to move the two items you've found into separate issues (linking back to this one) so we can more easily keep track of things.

**Comment by jbphet** [comment] 2019-03-27 16:20
Sure, I'm glad to put things in separate issues.  I'm assuming that I should put them in this repo (`WebAudio/web-audio-api`), let me know if not.  Also, to whom should I initially assign them?

**Comment by rtoy** [comment] 2019-04-11 18:20
Yes, any new issues you find should be in this repo.  You don't need to assign them to anyone because we go over this list at least once a week.  But feel free to assign @rtoy if you want.

I'm closing this issue out now because the two items you pointed out here (and separated into #1844 and #1845) are closed now.

Thanks for your work, and keep those bugs coming!

**Closed by rtoy** 2019-04-11 18:20 UTC
Labels: Needs WG review
