### ISSUE TITLE
Custom node

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api#789] opened 2016-04-07 21:55 UTC
Raise at WAC2016.

**Comment by hoch** [comment] 2016-04-15 16:46
Wait, is this about Composite AudioNode? (Subclassing/Composition)

**Comment by hoch** [comment] 2016-05-04 17:46
This is related to (or even a duplicate of) #251.

**Comment by hoch** [comment] 2016-06-07 23:27
Again, I think this issue can be closed. #251 is marked as 'ready for editing.'

**Comment by hoch** [comment] 2016-08-22 20:19
@joeberkovitz Could close this one with the chair hat on? :)

**Comment by joeberkovitz** [comment] 2016-08-23 18:53
Closing since duplicated by #113

**Closed by joeberkovitz** 2016-08-23 18:53 UTC
Labels: Feature Request/Missing Feature
