### ISSUE TITLE
[audioworklet] Clarify transition between AudioWorkletProcessorState

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#1451] opened 2017-11-16 21:49 UTC
https://webaudio.github.io/web-audio-api/#idl-def-audioworkletprocessorstate

Currently the spec only defines the meaning of each state. However, it would be useful to clarify the transition between them. This is a typical transition between states.

`pending` -> `running` -> `stopped`

We might want to clarify then this is irreversible; a `running` processor cannot go to the `pending` state again, and a `stopped` processor cannot to back to `pending` or `running` states.

`pending` -> `error` (construction failure)
`pending` -> `running` -> `error` (process callback failure)

Scenarios for the `error` state can be summed up to two cases above. Similarly, once a processor reaches to the `error` state, there is no way to recover.

**Comment by karlt** [comment] 2017-11-20 03:49
> a stopped processor cannot to back to [...] running states.

"running 	Indicates that the active source flag on the corresponding
                processor is true.

 stopped 	Indicates that the active source flag on the corresponding
                processor is false."

"At the conclusion of each call to the process() method, if [sic] the result
 of applying ToBoolean (described in [ECMASCRIPT]) to the return value is
 assigned to the associated AudioWorkletProcessor's active source flag."

A processor that has previously moved to stopped state by returning false
would still be called while it has connected inputs and so could return to
running state by returning true.  An example is described: "In this case,
process() SHOULD return true for some period of time after inputs is found to
contain zero channels."

See also case 4 at
https://github.com/WebAudio/web-audio-api/pull/959#issuecomment-260979231

I wonder whether "passive" and "active" might be more descriptive than
"stopped" and "running", but what is the purpose or use case for
distinguishing these two states?

**Comment by hoch** [comment] 2017-11-21 20:15
@karlt Thanks for reminding this. Perhaps I need to sit down and review the previous discussion. I feel like `passive` and `active` sound more abstract. Doesn't it?

**Comment by karlt** [comment] 2017-11-21 23:16
`stopped` and `running` are more concrete terms, yes, but I find `stopped`
misleading if `process()` may continue to be called on the processor.

Is there a need to distinguish these states, or would `pending`, `running`, and
`error` suffice?

**Comment by joeberkovitz** [comment] 2017-11-29 14:26
I think `stopped` still makes sense because another object in the global scope could examine the processor. There is no particular use case for this right now, but if we make other APIs visible in the AW global scope, this distinction could very likely become useful, and it does reflect a reality in the state machine of a processor (the active source flag).

**Comment by karlt** [comment] 2017-11-30 03:19
> I think stopped still makes sense because another object in the global scope
> could examine the processor. There is no particular use case for this right
> now, but if we make other APIs visible in the AW global scope, this
> distinction could very likely become useful, and it does reflect a reality
> in the state machine of a processor (the active source flag).

`processorState` is on the `AudioWorkletNode`, and I don't know what APIs you
have in mind, and so I don't follow how aspects of the AW global scope would
make a `stopped` state useful in the window scope.

If the client would like to have a means to determine in window scope the
state of the processor, then it could use the MessageChannel to provide this.

This is not a major issue though.  I mentioned it here because the name
`stopped` seemed to have already caused some confusion about the state, and
so there is the option of addressing this at the same time if the transitions
are to be spelled out explicitly.

**Comment by joeberkovitz** [comment] 2017-11-30 17:59
The WG talked about this today. We're thinking about whether to remove exposure of `stopped` altogether.

**Comment by hoch** [comment] 2017-12-07 04:45
I propose something like this:

```webidl
interface AudioWorkletNode : AudioNode {
  readonly attribute AudioParamMap parameters;
  readonly attribute MessagePort port;
  attribute EventHandler onprocessorerror;
};
```

1. States like `pending`, `running`, `stopped` can be easily checked in the logic in the processor code. It also can notify the node via MessagePort.
2. Since handling error in WorkletGlobalScope properly is currently impossible, it makes sense to have a dedicated event handler for the processor error.

**Comment by joeberkovitz** [comment] 2017-12-07 15:41
@hoch: would we want an event phrased in terms of status change, rather than error? The handler should presumably communicate any changes in status, not just the error case.

**Comment by hoch** [comment] 2017-12-07 17:47
@joeberkovitz My proposal was removing "processorState" from the spec. My arguments are:
1. Developers are highly likely to create their own states and use MessagePort for notification. `pending`, `running` and `stopped` - 3 states won't be enough to cover the all the use cases anyway.
2. There is no way to catch when `error` happens in the worklet global scope. We need a way of sending an event to the node when it happens, so developers can set up a logic accordingly.

**Comment by joeberkovitz** [comment] 2017-12-07 19:59
@hoch I see your point, thanks!

**Comment by rtoy** [comment] 2018-01-18 17:40
Pending discussion/conclusion of #1471

**Comment by hoch** [comment] 2018-02-23 20:13
@rtoy @mdjp @padenot

What's the resolution here? Are we fine with [the proposal above](https://github.com/WebAudio/web-audio-api/issues/1451#issuecomment-349861674)?

**Comment by mdjp** [comment] 2018-03-01 17:47
Confirmed that we resolve this with the proposal from @hoch [https://github.com/WebAudio/web-audio-api/issues/1451#issuecomment-349861674]

**Closed** 2018-03-28 16:31 UTC
Labels: Clarification (Requires change), In PR Review
