### ISSUE TITLE
ChannelCount, Mode, Interpretation for ChannelSplitterNode?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#861] opened 2016-06-28 16:08 UTC
The purpose of the `ChannelSplitterNode` is to take a multi-channel signal on its one input and separate them out into separate outputs with one channel on each.

But `channelCount`, `channelCountMode`, and `channelInterpretation` apply to the one input to the node.  This means you could end up taking a 5.1 source, downmixing to mono, and then having the one mono source going to output 1 and the remaining outputs having nothing.

Should users be allowed to change these?  This is probably ok on the principle of garbage-in/garbage-out.

However, I do think `channelInterpretation` should probably be changed to "discrete" instead of the current "speakers".

**Comment by mdjp** [comment] 2016-09-22 14:49
closed as duplicate of #975

**Closed by mdjp** 2016-09-22 14:49 UTC
