### ISSUE TITLE
[audioworklet] Initialization of `sampleRate` in AudioWorkletGlobalScope

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#1435] opened 2017-10-30 20:04 UTC
Consider this example:
```js
class MyProcessor extends AudioWorkletProcessor {
  static get parameterDescriptors() {
    return [{
      name: 'frequency',
      defaultValue: 440,
      minValue: 0,
      maxValue: sampleRate * 0.5
    }];
  }

  constructor() {
    super();
  }
  process() {}
}
```

The value of `sampleRate` in this example is evaluated when `audioWorklet.addModule(url)` gets called. So it is possible that there is no valid/active BaseAudioContext is running. Thus, `maxValue` of AudioParam becomes undefined.

Interestingly enough, having `sampleRate` and `currentTime` in AudioWorkletProcessor does not really solve the issue as well, so this could be a structural problem caused by the orthogonality of AudioWorklet and BaseAudioContext.

The spec also seem to be missing when `sampleRate` and `currentTime` are initialized and updated. I propose they are initialized to 0 when AudioWorkletGlobalScope is created, and `currentTime` is updated before every render quantum.

**Comment by joeberkovitz** [comment] 2017-11-02 16:35
Part of the issue could be that `parameterDescriptors()` accessor is static, which may make it impossible to ever have a well-defined `sampleRate` value at the time that it's called.

To discuss at TPAC.

**Comment by joeberkovitz** [comment] 2017-11-06 13:06
Here are some thoughts prior to Monday's WG meeting.

First of all, let me correct a misstatement I made on last week's call: as per the current specification, an `AudioWorkletGlobalScope` is already constrained to be associated with exactly one `BaseAudioContext`, so there is no problem identifying the context whose `sampleRate` and `currentTime` are to be surfaced. The problem is, as @hoch said, more to do with initialization sequence and static clearly at what point these properties become defined.

To @hoch's two options, I would add this one to consider: perhaps it's possible to execute the processor registration steps in https://webaudio.github.io/web-audio-api/#methods-13 lazily, such that they only occur after the AudioContext is fully initialized.

**Comment by hoch** [comment] 2017-11-06 16:59
@joeberkovitz I think my option 1 is sort of the lazy initialization of AWGS. To elaborate the idea:

1. By splitting "Fetch and Invoke Script" process in `worklet.addModule()` into "Fetch" and "Invoke Script when requested", this problem can easily be solved.
2. Then now we have a layering problem. Do we have to upstream this change to Worklet spec? Or should we just restrict this change within Web Audio API?

I am fine with overriding `worklet.addModule()` algorithm by our own two-phase process, but I don't know how Worklet folks feel about this.

@bfgeek WDYT?

**Comment by mdjp** [comment] 2017-11-06 17:47
Agreement on comments from @hoch but we need to establish wether this should be an upstream change or restricted to web audio. @hoch to find @bfgeek during TPAC to discuss.  We will come back to this issue later in the F2F

**Comment by hoch** [comment] 2017-11-07 00:22
@bfgeek and I discussed this issue in person. There seems to be no easy solution for it. I believed the splitting 'Fetch and Invoke Script' to two-step process, but it is not possible because `fetch`, [which is a part of in HTML spec](https://fetch.spec.whatwg.org/), requires a valid global scope to function correctly.

That leaves us two alternatives:
1. Move `worklet` to BaseAudioContext.
2. Specify `AudioWorkletGlobalScope.sampleRate` in the static getter will yield `0`.

At this point, I prefer to choose the option 2.

We can surely try to tackle the `fetch` algorithm in HTML spec to support our use case. That obviously requires a more rigorous review than a usual spec change.

**Comment by joeberkovitz** [comment] 2017-11-07 15:26
@hoch that's good to know. I think there are still some other possibilities besides your 2 alternatives above, so let's not frame it quite yet as "choose one of the above" (and neither of those options is very appealing; one is a big structural change, and the other basically gives up on context-relative parameter descriptors)..

First, note that the spec already says that every AWGS is associated with exactly one BaseAudioContext (see para. 2 of https://webaudio.github.io/web-audio-api/#AudioWorkletGlobalScope). Quoting here: _At least one AudioWorkletGlobalScope exists for each AudioContext that contains one or more AudioWorkletNodes._ (NB: this should say BaseAudioContext.)  There's also a Note that goes slightly further, stating, _every AudioWorkletGlobalScope is associated with a single BaseAudioContext, and with a single audio rendering thread for that context_.

I think this points to a couple more ideas:

  3. Have the spec explicitly state that a AWGS will only be created after the initialization of its owning BaseAudioContext. This is only a tiny step further than the existing stipulation of each AWGS being owned by only one context. It does not change any API signatures, and this is my preferred option at the moment.

  4. Do not permit `get parameterDescriptors()` to be invoked until the AWGS's associated BaseAudioContext has been initialized. This could be accomplished by obtaining the _node name to processor map_ variable on a just-in-time, only-if-needed basis, as part of the initialization sequence laid out in https://webaudio.github.io/web-audio-api/#instantiation-of-AudioWorkletNode-and-AudioWorkletProcessor. This would impose an additional async thread turnaround (with a blocking wait) as part of that sequence, but only upon the very first instantiation of a given node type.

**Comment by svgeesus** [comment] 2017-11-07 18:48
related: https://github.com/w3c/css-houdini-drafts/issues/510

**Comment by joeberkovitz** [comment] 2017-11-07 21:43
Summary of this morning's WG discussion:

Walked through construction and script loading for AWGS and AWN in detail. Options 1 (@hoch) and 3 (@joeberkovitz) felt like the nicest at first, with the difference being that option 1 requires each AudioContext to load its own scripts separately. So option 3 felt a little better at that time... but read on.

In the process we discovered that as per the Worklets spec (see step 10 of https://drafts.css-houdini.org/worklets/#dom-worklet-addmodule) there is forced construction of exactly one AWGS if none exist at the time of a `worklet.addModule()` call. Thus there can be at least one AWGS that doesn't have an owning AudioContext, if no AudioContexts have been constructed prior to calling addModule(). We reviewed all this with @bfgeek who explained that the forced construction guarantees up-front rejection of an addModule() call if scripts don't exist, don't parse, etc.  But he also says we could drop this scope on the floor and not use it, and thus preserve the guarantee of an owning context for all global scopes that are actually used by Web Audio.

But... the bigger issue is this: the way that parameter descriptors are currently retrieved from an AWP is not going to work, because their retrieval is currently tied to resolution of the promise returned by `addModule()`. And that resolution only occurs once -- even if there are many AudioContexts (each of which might have different parameter descriptors, for example if sampleRate is used to calculate min/max values). Given that param descriptors would need to be separately obtained for each context in the main thread, and that these are only available after each context's AWGS is separately initialized, this clearly shows that we need some way for the main thread to be informed of the completion of each separate initialization. Option 3 does not provide this, because we're still stuck with only one promise (from a single call to addModule), not one promise per AudioContext.

@hoch's option 1 (moving `worklet` to an attribute of `BaseAudioContext`) is therefore our preference right now. It solves a number of problems neatly, at some cost.

Pros:

- Every AWGS and its AWPs are explicitly connected to an owning BaseAudioContext, the one whose `AudioWorklet` is used to load the worklet scripts via `context.worklet.addModule()`.
- Promises from `addModule()` now resolve in a way that lets the main thread know when a context's global scope(s) is completely initialized.
- The acquisition of parameter descriptors for the context's _node name to parameter descriptor map_ can be tied to this promise resolution, allowing the descriptors to vary from one context to another.

Cons:

- Developers have to separately load AW scripts for each context that's going to use them and wait for these promises to resolve.
- Increased memory and performance load from per-context loading

**Comment by joeberkovitz** [comment] 2017-11-07 22:18
If we go this way, we need to add new spec language to do the following:

- At the end of `registerProcessor()`, call the `parameterDescriptors` static getter and queue a task on the main thread to add a new entry to the context's param descriptor map.
- Stipulate that the main-thread resolution of addModule()'s Promise is also a queued task, forcing it to only occur after the above queued tasks have been performed. This makes sure that all parameter descriptors are in place on the main thread by the time the promise is resolved.

That last point could be also addressed by amending the language used in the Worklet spec. See https://github.com/w3c/css-houdini-drafts/issues/418

**Comment by joeberkovitz** [comment] 2017-11-09 00:22
As we go over this territory, it's become apparent that `AudioWorklet` is not documented as an interface. I would appreciate others' thoughts on this choice:

1. `AudioWorklet` becomes an actual abstract interface which extends `Worklet`, but adds no attributes or methods.
2. We stop referring to `AudioWorklet` altogether and just talk about the "audio Worklet", which is a regular `Worklet` object belonging to `BaseAudioContext`. 

The CSS Paint specification approaches this question using option 2. I am not sure whether anyone made a conscious decision to diverge from this. It is not hard to move the spec in this direction, if that makes sense.

**Comment by joeberkovitz** [comment] 2017-11-09 00:30
I think I lean towards option 2. It doesn't make sense to define a subinterface that doesn't change its ancestor in some way, even if the concrete object implementing that interface behaves differently.

**Comment by hoch** [comment] 2017-11-09 17:47
I gave some thought on this. The simple reduction and reorganization might not work as we think. Here's the problem.

Keeping `AudioWorklet` interface might be necessary, because some HTML/DOM features are only exposed to AudioWorkletGlobalScope: [Event](https://dom.spec.whatwg.org/#interface-event), [MessagePort](https://html.spec.whatwg.org/multipage/comms.html) etc. They are exposed via `Exposed=(Window,Worker,AudioWorklet)`. If we remove AudioWorklet interface from the spec, then it needs to be changed to `Worklet`. Of course it leads to the wider discussion with Worklet/Worklet-variants folks. Their initial response on this issue was "no".

Here's my proposal:
1. Create `AudioWorklet` interface, which inherits from `Worklet`. We can potentially add audio-specific features in the future when needed. For example, PaintWorklet does randomization with global scopes whereas AudioWorklet does not. I think eventually they will diverge as people need more domain-specific features. For now, I don't think we have to define anything.
2. BaseAudioContext owns a [SameObject] getter of `audioWorklet` which is the type of `AudioWorklet`.
3. Keep changes in HTML/DOM to expose MessagePort, Event only to AudioWorklet.

**Comment by joeberkovitz** [comment] 2017-11-10 18:07
Thanks @hoch. That makes sense to me; as I thought about the many `Exposed=AudioWorklet` I began to worry that this would have ripple effects.

I'll make the rest of the changes you suggested and finish off the PR.

**Closed** 2017-11-30 17:23 UTC
