### ISSUE TITLE
Enable AudioContext to be created in a Worker

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#16] opened 2013-09-11 14:27 UTC
> Originally reported on W3C Bugzilla [ISSUE-19991](https://www.w3.org/Bugs/Public/show_bug.cgi?id=19991) Sat, 17 Nov 2012 17:12:35 GMT
> Reported by Jussi Kalliokoski
> Assigned to 

Currently there are several annoyances to scheduling in the Web Audio API. For example, if you want to play back a dynamic sequence, you would power it up with a setTimeout/setInterval, both of which are throttled to once per second when in a background tab. Now, if you set up a timer that happens once per second what happens if a reflow or other event delays the timer? To protect against this, you can schedule events for more than a second at a time, but it's a tradeoff for responsiveness of the application. Responsiveness or robustness is not a nice tradeoff to make.

A suggested approach to this problem has been to add a callbackAtTime() method to the AudioContext, but I fear that introducing yet another timer mechanism to the main thread won't help much. Say you setup a callback to trigger one second from the current time. Should it

a) Fire before the clock actually hits the specified time to be a bit more sure to make it in time?
b) Fire exactly when the clock actually hits the specified time? In this case, the desired target is most likely missed.
c) Fire after the time? This is a ridiculous idea. :D

Anyway, even that would be suspect to being delayed by other main thread events like reflows etc., being not much more reliable than a setTimeout(). I think we're going to get a lot of "no" sound from other working groups and browser vendors if the callbackAtTime() had no throttling rules, when browsers finally have painfully put those restrictions to place for existing main thread timer callbacks, so I don't think we'd get even that advantage.

Hence I'd suggest specifying access to the AudioContext interface from Web Workers, where one doesn't need to worry about main thread events delaying anything, nor about timer throttling.

For the time being, the Workers would obviously support less features (supporting MediaStreamSourceNode and MediaElementSourceNode in the Workers would require transferring these entities to the Worker as well). One option would of course be that AudioContexts would be defined as Transferrables, as well as a AudioNodes, letting graphs be shared across threads. This would probably actually be the best way to achieve this, provided we can eliminate race conditions by having value setters and getters exclusive to the thread that currently has the ownership of each node. But there aren't many critical features like this in the Web Audio API, which makes it a prime candidate for being a Transferrable.

**Comment by joeberkovitz** [comment] 2015-04-08 21:13
Quoting from an email from Ashley Gullen <ashley@scirra.com>:

We develop a HTML5 game engine and our goal is to ultimately have the entire engine running from a Web Worker, off the main thread.

There is progress on getting canvas rendering from workers specced. The last major hurdle to running an entire game engine in a worker is audio playback. Currently AFAIK Web Audio is only specced to work from the main thread, and it is a relatively complex API, so if a game engine is running in a worker there would need to be a bridge between the worker and the main thread with lots of postMessage going on, which could impact performance and add latency while adding complexity. Having Web Audio available in Web Workers would solve this. Has this been investigated yet?

Ideally AudioContext could be made available in WorkerGlobalScope. However I can immediately see a number of issues:

- integration with Media Elements would not be available (e.g. createMediaElementSource), because they are part of the DOM which is not available in a Worker
- integration with Media Streams would not be available, including from getUserMedia, since these are not available in a Worker (AFAIK)
- selection of audio input and output devices is currently only available on the main thread (although this may not be a problem if device ID strings can be posted to the worker)
- ideally types like AudioBuffer would be Transferrable

Implementation ideas:
- a WorkerAudioContext with the unsupported features removed (e.g. anything using media elements or media streams) but otherwise working identically to AudioContext
- a WorkerAudioContext with all features, but some way of integrating with media elements/media streams from the main thread (e.g. by ID strings/object URLs)
- a WorkerAudioContext with some kind of specialised WorkerMediaStream that can access an object URL created from the main thread and route audio from either a media element or media stream to the WorkerAudioContext
- a WorkerAudioContext with all features, including speccing Media Streams for workers! (possibly very difficult)
- a Transferrable AudioContextProxy that can be obtained from an existing AudioContext on the main thread and sent to a worker. Calls to AudioContextProxy would simply be forwarded to the existing AudioContext similar to what a postMessage implementation would do, so it's really using the same context. AudioContextProxy would also be missing media element/media stream features, but these could still be implemented from the main thread since it can use all features there. This is probably the simplest solution and significantly reduces the burden of bridging the APIs in JS (reducing the bridge to only the features necessary to cover media elements/media streams), but in the long term implementing MediaStreams in workers seems like it would be desirable too.

**Comment by joeberkovitz** [comment] 2015-04-30 16:31
Moved to next discussed on telcon today with @padenot @rtoy

**Comment by mitar** [comment] 2015-12-09 01:37
What is progress on this?

**Comment by mitar** [comment] 2015-12-09 01:39
Ah, I see #113 are where thing are happening.

**Comment by joeberkovitz** [comment] 2017-06-21 13:55
Closing as duplicate of #1098

**Closed by joeberkovitz** 2017-06-21 13:55 UTC
Labels: Feature Request/Missing Feature
