### ISSUE TITLE
Valid range for startInChannel for copyToBuffer and copyFromBuffer

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1884] opened 2019-05-15 16:20 UTC
In [startInChannel](https://webaudio.github.io/web-audio-api/#dom-audiobuffer-copyfromchannel-startinchannel) for both `copyToBuffer` and `copyFromBuffer`, an error is thrown if the value is *greater* than the length of the `AudioBuffer`.

When `startInChannel` is equal to the length, no error is thrown, but no data is copied either because the number of frames copied is `min(AudioBuffer.length - startInChannel, destinationa.length)`

I think it makes more sense to also throw if `startInChannel` also threw if it's greater than or equal to the AudioBuffer length.

I think the intent was that if `startInChannel` wasn't a valid index into the AudioBuffer, an error would be thrown.

**Comment by karlt** [comment] 2019-05-16 05:20
IMO the lack of error when there is no space in the buffer at `startInChannel` is consistent with the lack of error when there is not enough space (for the array contents) at `startInChannel`.

"the number of frames copied from source to the buffer is min(Nb−k,Nf)", which is still valid when k == Nb, but is not valid when k > Nb.  i.e. copying zero frames is not an error but copying a negative number of frames is, or `startInChannel` equal to `AudioBuffer.length` is a valid start offset to indicate zero frames.

**Comment by rtoy** [comment] 2019-05-16 14:53
Yes, you are right.  But I think the intent is clear:  `startInChannel` should be a valid index into the `AudioBuffer`.

I think we have the following options:
  1. Leave as is.
  1. Change it so `startInChannel` must be a valid index.
  1. Change it so if 0 elements would be copied an error is thrown.
  1. Don't throw on anything, allowing no elements to be copied silently.

I am opposed to option 1.  The others are ok with me.

**Comment by karlt** [comment] 2019-05-16 22:28
I'm not aware of anything to indicate intent that `startInChannel` should be an index that would identify at least one existing element in the AudioBuffer.  It is an "offset" from which to start copying.  An offset can validly identify the end of the array.

I'm not aware of any fundamental problem with the behavior currently specified.

If the spec needs to be modified, however, then I can see value in choosing not to throw even when `startInChannel` is greater than the length (option 4), because that would be more consistent with JS Array and TypedArray methods such as copyWithin()/splice()/slice()/subarray().

**Comment by hoch** [comment] 2019-05-20 20:57
> because that would be more consistent with JS Array and TypedArray methods such as copyWithin()/splice()/slice()/subarray().

I strongly agree, and this is how the last discussion ended.

**Comment by chrisguttandin** [comment] 2019-05-21 22:59
I meanwhile opened (and closed) an issue which was essentially a duplicate of this one. I opened it because the type of the error which is thrown (an IndexSizeError) made me think that something is wrong with the index and that this the reason why the error is thrown. That's why I came to the same conclusion as @rtoy that the error should be thrown as well when `startInChannel` equals the length.

**Comment by hoch** [comment] 2019-05-23 21:07
The way I see this, this method is an expansion of [`TypedArray.set()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/set) method. Once we pick the channel with `channelNumber`, the rest of process is identical to `targetArray.set(sourceArray, offset)`.

For that reason, I think it is sensible to follow what `TypedArray.set()` does. Here are my proposal:

1. Rename `startInChannel` to `offset`.
2. If the `sourceArray.length` + `offset` is greater than `targetArray.length`, throw RangeError. ([MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/set#Errors_thrown))
3. Copy the data from `sourceArray` to `targetArray` starting from `targetArray[offset]`.

**Comment by karlt** [comment] 2019-05-23 23:05
Thank you for finding that, @hoch.  That sounds a sensible option to me.

**Comment by rtoy** [comment] 2019-05-24 14:55
Doesn't this change the behavior of these functions quite a bit?

In both chrome and firefox:

```
x = new Float32Array(5)
y = new Float32Array(10)
x.set(y,3) => RangeError: Source is too large
```

For WebAudio the equivalent thing would be
```
b = new AudioBuffer({length: 5, sampleRate: 48000})
b.copyToChannel(y, 0, 3)
```
This doesn't throw an error today because the index 3 is a valid index into b.  And this would result in x[3:4] getting set with the values y[0:1].  Your proposal I think would throw an error here if you want it to match what `array.set` does.

I don't think we can break this part of the API now.

**Comment by karlt** [comment] 2019-05-27 04:09
I'd agree with @rtoy's implication that changing the spec to throw in a situation that does not currently throw is more risky than changing to not throw in a situation that does.

**Comment by hoch** [comment] 2019-06-03 19:53
I would argue for investigating the real-world breakage for this, but I think it's a bit late to do that.

**Comment by rtoy** [comment] 2019-06-03 20:05
I think only options 2 and 4 (from https://github.com/WebAudio/web-audio-api/issues/1884#issuecomment-493101285) are in play now.  We need to decide which. (Chrome does option 2.)

**Comment by karlt** [comment] 2019-06-03 20:41
```
a = new Float32Array(la)
b = new AudioBuffer({length: lb, sampleRate: 48000})
b.copyToChannel(y, 0, lb - la)
```
To introduce an exception for the la == 0 case (option 2) would be nonsensical because there is no error.

**Comment by rtoy** [comment] 2019-06-03 21:50
Did you mean `b.copyToChannel(a, 0, lb-la)`?

I guess the main question is whether to have to spec do what Chrome has been doing for some while now (chrome 43 or so), or to do what Firefox recently started doing, or just change the spec not to throw at all.

**Comment by karlt** [comment] 2019-06-04 03:36
> Did you mean `b.copyToChannel(a, 0, lb-la)`?

Yes.  Thank you for deciphering my intention.

> I guess the main question is whether to have to spec do what Chrome has been doing for some while now (chrome 43 or so), or to do what Firefox recently started doing, or just change the spec not to throw at all.

FWIW the Firefox implementation has always supported the case in https://github.com/WebAudio/web-audio-api/issues/1884#issuecomment-498418707

Authors familiar with TypedArray.set() will also expect this not to throw.

It sounds like the only option we would all consider acceptable is option 4.

**Comment by rtoy** [comment] 2019-06-13 15:41
Teleconf:  Just go with option 4.  This is a change in behavior.

**Closed** 2019-07-26 15:37 UTC
Labels: Clarification (Requires change), Editorial/Documentation
