### ISSUE TITLE
AudioWorkletGlobalScope is missing performance.now() (but has Date.now())

### ISSUE THREAD

**Issue by juj** [WebAudio/web-audio-api#2527] opened 2022-11-08 16:32 UTC
Calling `performance.now()` is failing in Audio Worklets. However the inferior `Date.now()` does exist there.

It would be great to get `performance.now()` there as well, since most audio applications are likely about calculating audio synthesis timing, so will be looking at precise wallclock times, rather than imprecise Date calculations.

**Comment by hoch** [comment] 2022-11-08 16:48
We're aware of the problem. The spec change will be presumably simple, but the impl might take a while.

Closing this as a duplicate of:  https://github.com/WebAudio/web-audio-api/issues/2413.

**Closed by hoch** 2022-11-08 16:48 UTC
