### ISSUE TITLE
(LinearEffectsUsingConvolution): Linear Effects using Convolution ought to be merged into other sections

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#97] opened 2013-09-11 14:28 UTC
> Originally reported on W3C Bugzilla [ISSUE-17384](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17384) Tue, 05 Jun 2012 12:04:13 GMT
> Reported by Philip Jägenstedt
> Assigned to 

Audio-ISSUE-100 (LinearEffectsUsingConvolution): Linear Effects using Convolution ought to be merged into other sections [Web Audio API]

http://www.w3.org/2011/audio/track/issues/100

Raised by: Philip Jägenstedt
On product: Web Audio API

https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/specification.html#Convolution

The "Background" section would fit well as a non-normative introduction to the ConvolverNode interface.

The "Motivation for use as a Standard" section looks rather out-of-place and would probably be OK to just remove.

The "Reverb Effect (with matrixing)" section contains what amounts to implementation requirements and should be moved to the ConvolverNode interface. Note that the "Mono to Copied Stereo" example looks very strange, where it looks like the number of output signals is determined not only by the input and impulse response, but also by how many channels the downstream input would like. This kind of negotiation is not documented anywhere, and looks unintentional.

**Comment by joeberkovitz** [comment] 2015-10-27 04:41
Duplicate of #125

**Closed by joeberkovitz** 2015-10-27 04:41 UTC
Labels: Editorial/Documentation, Ready for Editing, V1 (TPAC 2014)
