### ISSUE TITLE
Unclear semantics of duration param to AudioBufferSourceNode.start()

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#71] opened 2013-09-11 14:28 UTC
> Originally reported on W3C Bugzilla [ISSUE-23007](https://www.w3.org/Bugs/Public/show_bug.cgi?id=23007) Mon, 19 Aug 2013 14:38:11 GMT
> Reported by Joe Berkovitz / NF
> Assigned to 

One reading of the optional "duration" parameter AudioBufferSourceNode.start() is that it is a kind of syntactic sugar in which

   node.start(startTime, offset, duration);

behaves the same as:

   node.start(startTime, offset);
   node.stop(startTime + duration, offset);

Another view is that the duration paramter has slightly different semantics from the stop/start delta, although exactly how it differs is unclear. Gecko's interpretation is reflected in this WebKit bug:

  https://bugs.webkit.org/show_bug.cgi?id=111952

which states that the duration parameter is ignored if the buffer is in loop mode.

My feeling is that the syntactic-sugar interpretation (duration is equivalent stop/start delta) is the cleanest, most obvious behavior and was probably the original intention of the parameter, however objectionable the sugar flavoring may be.

**Comment by cwilso** [comment] 2015-06-02 17:03
Duplicate of #421, which has a solution.

**Closed by cwilso** 2015-06-02 17:03 UTC
Labels: Editorial/Documentation, V1 (TPAC 2014)
