### ISSUE TITLE
How to gapless change automation?

### ISSUE THREAD

**Issue by alkogolikov** [WebAudio/web-audio-api#689] opened 2016-01-06 15:33 UTC
Imagine than I have to change gain in two seconds from 0 (t = 0)  to 1 (t = 2). And in the middle of this action, for example in t=0.7 I suddenly need to change this automation and fade to zero in t = 1.5

What is the correct way? Cancell all existing automation, get curent value and create new automation from current value? If so what is correct vay to get current value? I've tried to inverpolate but when anomation is fast there are some gaps...

And is there way to cancel automation but freeze value, not to reset it?

**Comment by rtoy** [comment] 2016-01-06 17:27
This issue tracker is about issues with the spec, not a general WebAudio support tracker.

But your question does point to the fact that spec is not really clear on how things behave.  You might be interested in issue #344

**Comment by alkogolikov** [comment] 2016-01-06 20:23
I realize that, but spec is raw and I want help to make it better, to be suitable for real tasks like my own. As I saw, this behaviour differs in Chrome and Firefox, so problem in specs.

And I have another more general question: what will happen if I change automation during it execution. If I will add point in the past? Or in the future? Or if I have linear ramp and then add setValueCurveAtTime() over it?

**Comment by rtoy** [comment] 2016-01-06 20:51
Rather than asking for help for a problem, file more focused issues.  You have raised 3 good questions on how automation is under-specified.

For your last question about linear ramp and setValueCurveAtTime overlapping, we have an answer for that.  [You can't.](http://webaudio.github.io/web-audio-api/#AudioParam])

**Comment by joeberkovitz** [comment] 2016-01-14 17:17
@rtoy is willing to file bugs describing these issues at which point we'll close this one.

**Comment by rtoy** [comment] 2016-01-14 22:15
The question about canceling automations and freezing the value is #344.

The questions about getting the current value is #318.

I think there are existing bugs covering all of the issues raised here.

Closing this as a duplicate of #344 and #318.  Please re-open or file a new bug if you think this is incorrect.

**Closed by rtoy** 2016-01-14 22:15 UTC
Labels: Ready for Editing
