### ISSUE TITLE
WebAudio Worklets are Broken Demo (constructor horribly stalls the audio thread)

### ISSUE THREAD

**Issue by carlsmith** [WebAudio/web-audio-api#2269] opened 2020-10-30 00:31 UTC
I opened [an issue already][1], but it was closed on the assumption that I implemented the same bug half a dozen different ways :(

The API literally has no way of directly passing a track from the main thread to the audio thread, without stalling it horribly.

I've tried chopping the data up, and using `setTimeout` to sync the threads incrementally (using the `port` to communicate), but this caused the audio thread to stutter. I tried many different block sizes and timings already, but even if I get it working, it's always going to be relatively slow, as any developer has to prioritize the audio thread, and has no way of knowing how fast they can push data to it. It's basically a hack. The API should have an efficient way to transfer audio data to an audio processor.

[1]: https://github.com/WebAudio/web-audio-api/issues/2268
[2]: https://github.com/carlsmith/wabug

**Comment by carlsmith** [comment] 2020-10-30 03:28
In short, if there's no way to pass large structures (tens of MB) *to* the audio thread (without the audio dropping out), nor any way to initialize a similar structure *on* the thread, then it makes no difference how the data is transferred, as there's never going to be anything on the audio thread to store it in.

**Comment by carlsmith** [comment] 2020-10-30 18:23
One idea would be to add a `syncMessage` method to `port` that compliments `postMessage`, but can pass megabytes of data (in typed arrays/buffers) between the threads (less quickly), without blocking the audio thread.

There'd need to be something like an `onsync` callback (like `onmessage`) that can deal with each transferred block. Otherwise, the callback would need to do something with all of the data in one go. The `onsync` callback should probably take a couple of extra args (or a hash of them) that let it know where it's at with the transfer, and allowing it to compute offsets easily.

**Comment by carlsmith** [comment] 2020-10-31 00:28
One extra bit of info... I've tested a custom node with a constructor that takes a Wasm buffer, and creates a 10,000 page `WebAssembly.Memory` (with a corresponding `Float32Array` as an instance attribute), before initializing the Wasm engine (providing the memory as an import).

The new node can be instantiated (multiple times) while the demo node is playing music, *without* any issue, so it is possible to initialize adequately large typed arrays and memories on the audio thread. The only issue is getting data from the main thread to the audio thread.

**Comment by carlsmith** [comment] 2020-10-31 00:37
I'm going to look at using a shared array buffer again (rather than using `post` to send the data), and see if I can get it to work that way...

**Comment by carlsmith** [comment] 2020-10-31 02:54
Figured it out. Finally!

You have to create a `SharedArrayBuffer` on the audio thread, and post it to the main thread, then write to that. If the main thread sends the data to the audio thread, it will drop out.

**Comment by carlsmith** [comment] 2020-11-02 20:49
Sorry. That doesn't work. I thought it did, but it still drops out sometimes.

**Comment by padenot** [comment] 2020-11-05 19:08
What you're looking for is `postMessage` transfer list to be able to **transfer** a buffer to another thread. This has been available since around 2011, and has nothing to do with `AudioWorklet`. https://developer.mozilla.org/en-US/docs/Web/API/Transferable has more info.

This is essentially sending a pointer to the data to another thread, so to speak: here to the audio real-time thread, but it's the same for workers (any type of worker).

https://paul.cx/public/transfer.html shows the basics of operations. A button to start the context, a button that sends a new 100MB array with values going to 1 to 104857600. You can mash the second button and it doesn't glitch (modulo browser bugs as usual, that should be filed in the respective browser bug tracker).

A [bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1587752) prevents this from working as it should (but will be fixed). If you need this today, here is a variant of the page above https://paul.cx/public/transfer3.html, that is using a `SharedArrayBuffer`, not to share data between threads, but to sidestep this bug.

**Closed by padenot** 2020-11-05 19:08 UTC

**Comment by carlsmith** [comment] 2020-11-06 00:47
> https://paul.cx/public/transfer.html shows the basics of operations. A button to start the context, a button that sends a new 100MB array with values going to 1 to 104857600.

It glitches every time I press it. I know my [laptop's specs][1] are not particularly impressive, but I have no issues with other audio software.

[1]: https://support.apple.com/kb/sp678?locale=en_GB

**Comment by rtoy** [comment] 2020-11-06 15:35
I can confirm that @padenot's demo does glitch on Chrome 87 (mac OS).   However, when I visit chrome://flags and search for "realtime" and enable "Use realtime priority thread...", the glitch goes away.  If I press the "send 100 MB" button constantly, then I do hear an occasional glitch.

I think Chrome will switch to realtime priority by default soon.

**Comment by carlsmith** [comment] 2020-11-08 18:04
Thanks for looking into this, @rtoy.

Even with realtime threads enabled, I still get occasional glitches on my machine, and the demo only sends 100MB. That's fine for my application, but the API does not limit `postMessage` to 100MB. Ideally, you'd at least be able to pass a Wasm memory, which is currently up to 4GB.

The API effectively overloads `postMessage` so it has two responsibilities: It has to handle small messages (with low latency), and huge arrays (without blocking the audio thread).

I guess it's possible to use some heuristic under the hood to pick an algorithm, based on the size and shape of the argument (to `postMessage`), but I don't understand things well enough to comment on the practicalities of doing that. Alternatively, the API could just define separate methods (something like `postMessage` and `syncMessage`).
