### ISSUE TITLE
PreservePitch in web Audio API

### ISSUE THREAD

**Issue by Madhuri-RR** [WebAudio/web-audio-api#2564] opened 2024-01-08 06:53 UTC
How to preserve pitch unchanged when playback rate of audio is increased.

Now if I increase the playback rate pitch is also increasing.

**Comment by chrisguttandin** [comment] 2024-01-08 09:28
I think this is already discussed in #2487.

**Comment by hoch** [comment] 2024-02-08 17:42
Yes. This is a duplicate of #2487. Closing.

**Closed by hoch** 2024-02-08 17:42 UTC
Labels: status: needs discussion
