### ISSUE TITLE
atThisTime

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api#2544] opened 2023-03-27 16:09 UTC
Originally reported by Siim Petser, copied here with permission

**Describe the feature**
> Sorry to bother you but you seem to be the right contact in w3c. It's
> gonna be one time only post and wont happen again:)
>
>  The issue with timing currently with the api is:
>  you tell the api to start doing something x seconds after making the
> request.
> This is creates a bunch of problems.
>
> Maybe it would be possible to tell the api not to start doing stuff
> after x seconds but
> instead, tell it to do a thing at a certain time?
>
> instead:
> `source[theNote].start(0.7 + noteTime+properTimeForFiring-cutLag+firstLag);` - its a mess.
>
> something like this:
> `source[theNote].start(atThisTime);` atThisTime would be the timestamp,
> a concrete time.

**Is there a prototype?**
No

**Describe the feature in more detail**
(none provided)

**Comment by laadida** [comment] 2023-03-31 17:34
I just wanted to add a comment why a strict time version of the "start" command would be a nice addition.
True, it is possible to get accurate timing right now - it's a bit of extra struggle, but possible.
But people tend to have nice fast machines for coding, and there (when not a ton experience earned yet in this sensitive matter) the timing mistakes wont be apparent and may be difficult to test even. That strict timing would eliminate hopefully such pitfalls. Or at least help to greatly reduce the apps that work very well on last years Macs but not at all on older computers.
Even when testing on those older machines by ear, the tester sometimes can be fooled when again, not enough experience has been earned.

**Comment by padenot** [comment] 2023-04-03 11:43
This is already how it works today, I'm not sure what the problem is. The first argument is a time in the timeline of the `AudioContext`'s `currentTime` attribute.

If you want to do something as soon as possible, you do: `node.start(0);` (or any value that's lower than the `AudioContext`'s `currentTime`).
If you want to do it at time `1234.0` seconds, you do `node.start(1234.0);`.
If you want to do something 10 seconds from now, you do `node.start(audioContext.currentTime + 10.0);`.

**Comment by GeorgeTailor** [comment] 2023-04-03 11:49
hmm, I have a tablature player app where a user can upload a tab with multiple tracks. One of those documents had 8 tracks, so I create 8 separate audioContexts, each with it's own routing through additional filters such as amp, equalizer and a couple of others. Additionally, before playing anything, I create the sound from scratch, meaning I start only with frequency, send it to a worker and then create an AudioBuffer that is played through audioContext route at a certain time.
This is repeated for all 8 tracks, sometimes there were 16th notes at 160-180 bpm, so quite a lot of notes to generate for each track + additional audioContext for a metronome.

I tested it on iPhone 8, which was released in 2017 and it worked quite well, I haven't experienced any difficulties in making sure it plays simultaneously, apart from initial struggle to set everything up properly and calculate proper timing. Sure, iPhone 8 has 2 ARM cores for processing, but I guess all current devices have at least a couple of them, everything else is just so old it barely boots up OS. And besides that, I don't even use WASM with c++ or rust to generate stuff, it's pure JS and is still fast enough.

Do these ~2ms (a possible lag between tracks/audioContexts) make any difference even if a human cannot perceive them?

**Comment by laadida** [comment] 2023-04-03 15:38
If there's a loop (like metronome), it's only sensible to run it with setTimeout. This works well with Macs (recent ones at least) but with Windows machines (somewhat older), the lag can be over 10 ms easy. 

Currently, when telling node.start(1234.0), it would be then in 1234.0 seconds + and added lag. Also there is some lag from buffering too. So, there must be a compensation fix. And here the trouble starts - hard to test, easy to make a mistake. Easy to pass a wobbly product. 

But when telling node.startAtTimestamp(1234.0), then it would start when context.currentTime has reached 1234.0. That would cut the lag-fixing problem away cleanly.

Older  devices don't go anywhere. Have to care. Or can't sign a promise of an accurate thingy.

**Comment by padenot** [comment] 2023-04-03 15:48
> Currently, when telling node.start(1234.0), it would be then in 1234.0 seconds + and added lag. Also there is some lag from buffering too. So, there must be a compensation fix. And here the trouble starts - hard to test, easy to make a mistake. Easy to pass a wobbly product.

No, this is incorrect, if `node.start(1234.0)` is in the future, the audio will start at precisely `1234.0` seconds, in the timeline of the `AudioContext.currentTime`. Then there is the audio output latency, that needs to be accounted for separately (see below).

There also is no buffering in the Web Audio API itself, except what is accounted for using the audio output latency attributes.

Your third paragraph describes precisely how it works today.

Implementing metronomes with a loop is a mistake, and in general, implementing anything that needs to be extremely precise with `setTimeout` is also a mistake, because `setTimeout` is not precise by design. Please refer to https://blog.paul.cx/post/metronome/ and more importantly the linked articles to understand how scheduling works and to use the best design for your problem, and https://blog.paul.cx/post/audio-video-synchronization-with-the-web-audio-api/ to understand how to compensate for the audio output latency on the web.

**Comment by laadida** [comment] 2023-04-03 16:34
Thanks for clearing it out. I'm such a newbie:)

My metronome is here:
https://noodid.ee/MetronomeV2/metronome.html

Loops with setTimeout, fixed with window.performance.now() .... It does work nicely on 15 years old celeron:)

But thanks, 
Siim

**Comment by padenot** [comment] 2023-04-06 16:07
We can close this now.

**Closed by padenot** 2023-04-06 16:07 UTC

**Comment by lubobill1990** [comment] 2023-10-18 10:25
> hmm, I have a tablature player app where a user can upload a tab with multiple tracks. One of those documents had 8 tracks, so I create 8 separate audioContexts, each with it's own routing through additional filters such as amp, equalizer and a couple of others. Additionally, before playing anything, I create the sound from scratch, meaning I start only with frequency, send it to a worker and then create an AudioBuffer that is played through audioContext route at a certain time. This is repeated for all 8 tracks, sometimes there were 16th notes at 160-180 bpm, so quite a lot of notes to generate for each track + additional audioContext for a metronome.
> 
> I tested it on iPhone 8, which was released in 2017 and it worked quite well, I haven't experienced any difficulties in making sure it plays simultaneously, apart from initial struggle to set everything up properly and calculate proper timing. Sure, iPhone 8 has 2 ARM cores for processing, but I guess all current devices have at least a couple of them, everything else is just so old it barely boots up OS. And besides that, I don't even use WASM with c++ or rust to generate stuff, it's pure JS and is still fast enough.
> 
> Do these ~2ms (a possible lag between tracks/audioContexts) make any difference even if a human cannot perceive them?

By the way, it would better to use the same audio context for all tracks, so that the content time are aligned.
