### ISSUE TITLE
Clarification on GainNode's gain parameter

### ISSUE THREAD

**Issue by iccir** [WebAudio/web-audio-api#506] opened 2015-04-03 01:28 UTC
In the current documentation:

    Represents the amount of gain to apply. Its default value is 1 (no gain change).
    The nominal minValue is 0, but may be set negative for phase inversion. The 
    nominal maxValue is 1, but higher values are allowed (no exception thrown).

I found this a bit confusing as `minValue` and `maxValue` are listed nowhere else in the documentation.  I understand that the GainNode is intended to be a simple multiplier, and that a +6dB boost should be possible by setting gain.value to `1.995`, or a -3dB attenuation is `0.7079`, or a phase inversion at +0dB would be `-1`.  However, should this relationship be explicitly spelled out?  Is an implementor of WebAudio required to boost the gain for values over 1.0?  Or are they just "allowed" with no exception thrown.

Is implementation of the phase inversion required?

**Comment by hughrawlinson** [comment] 2015-04-03 02:50
So boosts seem like they could open a whole can of worms. If you actually boost the gain, every other node in the API would have to support signals of any arbitrary magnitude (this may already be the case, I'm not sure) which could be fine or could also cause implementation problems (i.e. what if the magnitude is higher than the highest value that a sample can be represented as, do we have to account for like 128 bit numbers, etc). It would also mean that when audio which has been boosted gets to the DAC and hasn't been normalised, that people could end up accidentally sending extra-large values to their speakers, which opens up a world of pain in potential for new malware in the web (ruining dacs of people who open a website with their volume on full). That, or there'd have to be a limiter or a hard clip on the DAC which would not be fun to deal with in certain use cases.

Or there may be ways of providing for boosts without running into any of their problems, those were really just my first impressions not backed by anything other than my own assumptions.

As for phase cancellation and attenuation, those are good uses for gain :)

**Comment by notthetup** [comment] 2015-04-03 03:25
On the other hand, the boost is super useful for doing stuff like AM and FM. The output of your message oscillator would usually be [-1,1] but you'd need to be able to multiply it (Gain.gain.value = multiplier) with the amount of modulation you want. 

I believe the lack of a strict upper limit of the gain value was created purposely for this this use case.

**Comment by hoch** [comment] 2015-04-03 03:55
As @notthetup mentioned, being able to boost the gain is essential for the modulation. This is by design - I haven't seen any computer music language that limits gain inside of audio graph.

> That, or there'd have to be a limiter or a hard clip on the DAC which would not be fun to deal with in certain use cases.

I will be very sad if we have to put a limiter on the output of the destination node in order to prevent some pages from ruining the output device. I don't think we have that kind of problem any more unless you're dealing with PA systems. More importantly, usually limiters with look-ahead introduce some amount of latency based on the design and also dynamic processors are really difficult to spec as a standard. (See what we have for DynamicCompressor in the spec.)

I believe shaping/balancing overall gains should be the developer's share and putting something vague at the end of audio graph is not a right thing to do.

**Comment by iccir** [comment] 2015-04-03 04:03
Not having the ability to boost gain (at all) would be bizarre, in my opinion.  As @notthetup mentioned, there are legitimate cases where this is needed.  Even a simple mixer app might need to boost a certain channel by +0-12dB.

Per the existing specification, audio buffers use 32-bit floating point numbers with a nominal range of [-1, +1] (section 2.8).  Hence, the overflow/underflow issue of working with SInt16 buffers shouldn't come into play with current implementations, although there is no language in the specification that states nodes cannot use SInt16 internally.

There are already ways to boost individual samples above 1.0 or below -1.0.  For example, I could use multiple BiquadFilter nodes.  Or I could combine two duplicate or correlated signals.  Or the wet mix coming back from a ConvolutionNode combined with the dry signal could push above 1.0.

Perhaps Section 3.2 needs to be expanded, however :)

**Comment by padenot** [comment] 2015-04-03 09:30
Yeah no any finite value for the gain is legal in current implementations I think.

It's not clear to me what:

> The nominal maxValue is 1, but higher values are allowed (no exception thrown).

means (or meant to mean maybe ?). This is the only reference to the _nominal `maxValue`_ concept. My guess is that it's bogus and should be removed.

Also, there is an issue for speccing nominal ranges for `AudioParam`s.

**Comment by iccir** [comment] 2015-04-03 12:18
Note: I completely missed the text in 2.6 above the IDL:

> Each sample of each channel of the input data of the GainNode must be multiplied by the computedValue of the gain AudioParam.

That clarifies my questions about explicitly spelling out the multiplication.

**Comment by hughrawlinson** [comment] 2015-04-03 14:56
> I will be very sad if we have to put a limiter on the output of the destination node in order to prevent some pages from ruining the output device. I don't think we have that kind of problem any more unless you're dealing with PA systems.

We probably need to check whether this is actually a problem in any consumer hardware and then probably address it in the spec. A limiter would really not be ideal, but if potentially outputting values >1 has the potential to wreck anyone's hardware at all, we should definitely fix it.

Also, is a PA system not a valid use case for the API? I can see it being used by artists and musicians for installation pieces likely to use PA systems.

**Comment by notthetup** [comment] 2015-04-03 15:52
No idea why I said limiter when I meant to say that there should be some form of clipping to 1. I should stop commenting on issues after midnight. :(

**Comment by hoch** [comment] 2015-04-03 16:25
@hughrawlinson Let me clarify a bit more - I said _"I don't think we have that kind of problem any more"_ because many audio interfaces out there now equipped with some form of overload protection. I can't guarantee or speak for 'any consumer hardware' though, but I think we have passed that age.

Also I didn't say PA system is not a valid use case. I should've mentioned that one needs extra care for balancing/shaping gains in that specific case. We might want to mention that in the spec as a note.

**Comment by hughrawlinson** [comment] 2015-04-03 17:20
Thanks for the clarification @hoch :) There are great benefits and also huge potential problems associated with assuming that every user will have overload protection on their DAC, I just hope that mentioning that devs should be careful in the spec is enough.

**Comment by iccir** [comment] 2015-04-04 00:40
One thing to keep in mind: even if you pass a large floating point value to `AudioContext.destination`, and the browser's implementation passes that unmodified to the system, there is no guarantee that it won't be clipped to 1 at the OS level.

Many DACs have a native format of 16-bit or 24-bit signed integer, with 32767 or 8388607 representing 0dBFS.  Since there is no way to represent values greater than 0dBFS, the OS will either clip to 1.0 before the float->int conversion, or apply some kind of limiter.

`AudioContext.destination` isn't a direct connection to the speakers or DAC, it's plugged into the OS's mixer.

**Comment by joeberkovitz** [comment] 2015-06-01 17:08
Now we have min/max values for gain of +/- infinity, closing since there's no remaining issue.

**Closed by joeberkovitz** 2015-06-01 17:08 UTC
