### ISSUE TITLE
How to debug audio node connections?

### ISSUE THREAD

**Issue by lukephills** [WebAudio/web-audio-api#575] opened 2015-08-15 17:01 UTC
I'm working on a large scale music app and I'm having trouble with some nodes not connecting and disconnecting properly.

Is there a method in web audio to see a list of current connections a AudioNode has?

I've tried using Firefox's Developer browser as this shows a view of all current connections but the problem is that it's viewer really can't handle more than about 15 connections.

It would be great if there was something like: osc.connections(); which would return an array of nodes the osc is connected to.

Any help is much appreciated, thanks!

**Comment by padenot** [comment] 2015-08-17 10:44
I'd say you can write you debugging tool yourself that would do exactly what you need. In fact, if you look at the code for the Web Audio Devtools in Firefox (or the web audio debugging extension for Chrome, they are using essentially the same technique), you can see how it's done.

The Web Audio API has no built-in introspection features for now, and while it's been considered, we are currently focusing on other aspects.

https://github.com/WebAudio/web-audio-api/issues/256 can be of historic interest.

Anecdotally, I've use the Firefox devtools to debug graphs with hundreds of nodes, there might be something fishy somewhere.

**Comment by padenot** [comment] 2015-10-14 11:53
Closing this as duplicate of #256.

**Closed by padenot** 2015-10-14 11:53 UTC
