### ISSUE TITLE
Chrome implementation: AudioParam.cancelScheduledValues(currentTime) "sometimes" does not clear AudioParam.setValueCurveAtTime

### ISSUE THREAD

**Issue by JohnWeisz** [WebAudio/web-audio-api#1218] opened 2017-04-28 23:11 UTC
This is a minor issue I encountered today in Chrome's implementation (57.0.2987.133) of the Web Audio API. Basically, if we do this:

```js
audioParam.setValueCurveAtTime(..., audioCtx.currentTime + t, d);
```

and sometime later, while the automation curve is still in progress (that is, `d` is yet to elapse) do this:

```
audioParam.cancelScheduledValues(audioCtx.currentTime);
audioParam.setValueAtTime(0, audioCtx.currentTime);
```

then we "sometimes" get an error similar to this:

 > setValueAtTime(0, t1) overlaps setValueCurveAtTime(..., t2, d)

where `t1 > t2` but `t1 < t2 + d`. The occurrence of the error seems to be completely random and does not seem to be related to precision and rounding errors (it also occurs with a small offset). However, if put into a "retry" loop, every single iteration will throw, which leads me to believe the error is caused by an unfortunate combination of curve and curve duration.

Now, if we do this instead:

```js
audioParam.cancelScheduledValues(0);
```

then everything seems to work reliably and flawlessly. We are still doing stress tests, but no errors so far. Unfortunately, I'm unable to setup a reliable mcve right now, but might attempt do one tomorrow. Any idea what could be causing this minor annoyance?

-----

Additionally, an interesting correlation I've discovered when running two such automation chains in parallel, one with `cancelScheduledValues(0)`, one with `cancelScheduledValues(audioCtx.currentTime)`, is that when the erroneous latter one throws its error, the working former one causes a minor clicking sound (when used to automate the `gain` parameter of a `GainNode`, e.g.).

**Comment by rtoy** [comment] 2017-04-29 05:04
Is this an error in the spec or a bug in Chrome?  If the former, can you clarify what you think the problem is?  If the latter, you should file a bug for Chrome at http://crbug.com/new with this description and a repro case if possible.

**Comment by joeberkovitz** [comment] 2017-05-11 16:46
Closing since this appears to be an implementation bug, not a spec issue.

**Closed by joeberkovitz** 2017-05-11 16:46 UTC

**Comment by hadrienj** [comment] 2017-09-25 13:47
@JohnWeisz Do you have more information on that issue? Did you finally fill a bug?

I have a similar problem since chrome 57 but this seems unrelated to `audioParam.cancelScheduledValues(0);`. The error is the same (`setValueAtTime(...) overlaps setValueCurveAtTime(..)`). I have difficulties to isolate the issue but it seems produced on a random basis. I create a lot (hundreds) of pure tones with random jitters and the scheduling gives me that error since version 57. 

Thanks!!

**Comment by joeberkovitz** [comment] 2017-09-25 13:56
@hadrienj @JohnWeisz please follow @rtoy's advice to take this up on the Chrome issue list, it's not a specification matter and the Chrome team is not going to be looking here for bugs they should fix.

**Comment by hadrienj** [comment] 2017-09-28 15:28
Ok thanks. For reference, I reported the problem [here](https://bugs.chromium.org/p/chromium/issues/detail?id=768740).
