### ISSUE TITLE
Be explicit on how browsers should handle "priming samples"

### ISSUE THREAD

**Issue by jakearchibald** [WebAudio/web-audio-api#1091] opened 2016-11-29 11:34 UTC
https://jakearchibald.github.io/aac-decode-bug/

Chrome stable, Firefox and Edge display a large gap at the start of the decoded AAC. This is added by the encoder as [a series of priming samples](https://developer.apple.com/library/content/documentation/QuickTime/QTFF/QTFFAppenG/QTFFAppenG.html).

Question is, should these priming samples be present in the decoded audio? The Apple document above says:

> a playback system must trim the silent priming samples to preserve correct synchronization

So I guess it depends on who the playback system is. Is it the browser when it decodes, or is it the web audio API user that calls `start()`.

My gut feeling is that Safari is doing the right thing, it certainly feels the most developer-friendly. If it's decided that the gap should be present, we must have an easy way to access this metadata so we know it's there and can skip it.

**Comment by padenot** [comment] 2016-11-29 13:43
This will probably be handled as part of the grand Media Decoder spec we've planned for v.next.

**Comment by rtoy** [comment] 2016-11-29 16:46
I think this is pretty complicated, at least after raising the issue with the ffmpeg developers a while back. (Chrome uses ffmpeg for decoding audio.) They said at the time that it was fairly difficult because the meta data was optional so there was no way to know for sure if the encoded stream actually included it.  If the meta data included the information, then ffmpeg would remove the priming frames.  

There are also remainder frames at the end, and the developers said that couldn't be reliably removed either.

Oh, this was for aac and mp3.  For ogg, ffmpeg produces the expected output. I think Opus and FLAC decoder produces the expected output.

**Comment by jakearchibald** [comment] 2016-12-01 08:44
@padenot in the meantime, do you know whether browsers should remove these gaps as part of web audio decoding, or is that still up for debate? A decision here would be useful to point the various browsers at and try and get some consistency.

**Comment by padenot** [comment] 2016-12-01 15:17
@jakearchibald, we (some people at Mozilla) are currently investigating a number of formats, codec specifications, bad encoders present in the wild, that kind of thing.

The idea here is that we should be able to roundtrip to wav (wav -> compressed format -> wav) and have the same file (more or less, of course taking the fact that compression can be lossy).

It may be that it is not feasible, and that for some formats, UAs will have to use heuristics.

**Comment by JohanRonstrom** [comment] 2016-12-09 11:15
We are currently trying to solve this in our products, for mp3 (LAME tag) and m4a (ITUNSMB tag).

In files where the tags do show up as expected (as seen with ffprobe), getting the start value from webaudio would be a huge first improvement.

We do of course want decodeAudioData to be able to load the audio as intended and specified by the encoder (trimmed).

**Comment by notthetup** [comment] 2016-12-12 00:08
Semi-relevant blog post related to this about MAD (libmad). Not sure if any UA uses libmad, but it seems that it also had some issues with priming samples.

https://thebreakfastpost.com/2016/11/26/mp3-decoding-with-the-mad-library-weve-all-been-doing-it-wrong/

**Comment by rtoy** [comment] 2016-12-12 17:32
Chrome's WebAudio implementation currently uses ffmpeg to handle all of the decoding.  Adding heuristics in WebAudio is not the preferred approach since the implementation currently doesn't need to know anything about the contents of the file except for the estimated duration.  The removal of these things are best handled by ffmpeg.

**Comment by hoch** [comment] 2016-12-19 17:35
I agree with @rtoy here. I had to use 'heuristics hack' to address the M4A container priming frames, but it backfired. (A simple OS update will ruin the fix.)

Even if we handle this issue at the level of unified decoder (i.e. FFMPEG) in Chrome, developers still have to fight the cross-browser inconsistency. It is a sad situation, but developers have to sniff the platform/browser or try to decode a short silent file to see the decoded result.

:(

**Comment by mdjp** [comment] 2018-10-25 14:17
This is not a spec level problem, but it may be worth adding a note to the spec to ensure that developers are aware. This would also have to be addressed in any new encoder API.

**Comment by rtoy** [comment] 2019-06-25 23:06
F2F: Do what @mdjp says and add a note.

**Comment by mdjp** [comment] 2019-09-17 07:52
Should be handled by web codec.

**Closed by mdjp** 2019-09-17 07:52 UTC
Labels: Architectural/Fundamental (Breaking change), Clarification (Requires change), Theme - Encoding/Decoding
