### ISSUE TITLE
MediaElementAudioSourceOptions's mediaElement member should be required

### ISSUE THREAD

**Issue by foolip** [WebAudio/web-audio-api#985] opened 2016-09-20 09:24 UTC
https://webaudio.github.io/web-audio-api/#MediaElementAudioSourceNode

```WebIDL
dictionary MediaElementAudioSourceOptions {
  required HTMLMediaElement mediaElement;
};
```

The prose even says "This must be specified."

@rtoy

**Comment by padenot** [comment] 2016-09-20 10:08
Duplicate of #981.

**Closed by padenot** 2016-09-20 10:08 UTC
